-- 코드를 입력하세요
SELECT  B.AUTHOR_ID,
        A.AUTHOR_NAME,
        B.CATEGORY,
        SUM((S.SALES * B.PRICE)) AS TOTAL_SALES
FROM    BOOK AS B
JOIN    AUTHOR AS A
ON      A.AUTHOR_ID = B.AUTHOR_ID
JOIN    BOOK_SALES AS S
ON      S.BOOK_ID = B.BOOK_ID
WHERE   YEAR(S.SALES_DATE) = 2022
AND     MONTH(S.SALES_DATE) = 01
GROUP BY    B.AUTHOR_ID, B.CATEGORY
ORDER BY    B.AUTHOR_ID, B.CATEGORY DESC