WITH TOTAL_USERS_2021 AS (SELECT  INFO2.USER_ID
                         FROM    USER_INFO INFO2
                         WHERE   YEAR(JOINED) = '2021')

SELECT  YEAR(SALE.SALES_DATE) AS YEAR
        , MONTH(SALE.SALES_DATE) AS MONTH
        , COUNT(DISTINCT SALE.USER_ID) AS PUCHASED_USERS
        , ROUND(COUNT(DISTINCT SALE.USER_ID ) /
                (SELECT COUNT(U2.USER_ID)
                 FROM   TOTAL_USERS_2021 AS U2)
                , 1) AS PURCHASED_RATIO
FROM    ONLINE_SALE SALE
JOIN    USER_INFO INFO
ON      INFO.USER_ID = SALE.USER_ID
WHERE   1 = 1
# AND     INFO.USER_ID IN (SELECT U2.USER_ID
#                          FROM   TOTAL_USERS_2021 AS U2)
AND     YEAR(INFO.JOINED) = '2021'
GROUP BY    MONTH
ORDER BY    YEAR, MONTH