# -- 코드를 입력하세요
SELECT  FH.FLAVOR
        # , SUM(FH.TOTAL_ORDER) + SUM(J.TOTAL_ORDER)
FROM    FIRST_HALF AS FH
JOIN    JULY AS J
ON      J.FLAVOR = FH.FLAVOR
GROUP BY    FLAVOR
ORDER BY    SUM(FH.TOTAL_ORDER) + SUM(J.TOTAL_ORDER) DESC
LIMIT 3

# SELECT FLAVOR, SUM(TOTAL_ORDER)
# FROM JULY
# GROUP BY FLAVOR
# ORDER BY SUM(TOTAL_ORDER) DESC
# LIMIT 3

# SELECT *
# FROM JULY