-- 코드를 입력하세요
SELECT  U.USER_ID,
        U.NICKNAME,
        B.TOTAL_SALES
FROM    USED_GOODS_USER U
JOIN    (SELECT     WRITER_ID,
                    SUM(PRICE) AS TOTAL_SALES
        FROM        USED_GOODS_BOARD
        WHERE       1=1
          AND       STATUS = 'DONE'
        GROUP BY    WRITER_ID) B
  ON    B.WRITER_ID = U.USER_ID
WHERE   B.TOTAL_SALES >= 700000
ORDER BY    B.TOTAL_SALES